---
title: "Appex 06"
format: 
  html:
    self-contained: true
editor: visual
---

## 

```{r}
#| label: load-packages

library(tidyverse)

```

Fill in the dataset below with the values from your sample:

```{r}
#| label: create-data
circle_data <- data.frame(
  frequency_score = c(1, 2, 3, ...) # replace these values with your 20 observations, with commas in between
)
square_data <- data.frame(
  frequency_score = c(1, 2, 3, ...) # replace these values with your 20 observations, with commas in between
)

bead_data <- bind_rows(circle_data, square_data) |>
  mutate(group = rep(c("circle", "square"), each = 20))
```

Visualize your data

```{r}
#| label: visualize

mean_table <- bead_data |>
  group_by(group) |>
  summarize(m = mean(frequency_score))

ggplot(bead_data, aes(x = group, y = frequency_score)) + 
  geom_point(alpha = 0.5) + 
  geom_point(data = mean_table,
             shape = "square", 
             size = 3,
             color = "orange",
             aes(x = group, y = m)) +
  labs(x = "Bead shape", y = "Frequency score")
```

Fit your simple linear regression model 
```{r}
#| label: fit-model

mod <- lm(---- ~ -----, data = bead_data)
mod
```

Calculate the confidence interval for the slope

```{r}
#| label: confidence-interval

summary(mod)

-------(mod)

```
